language: node_js
node_js:
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: FAKE_API_KEY
  app:
    master: cse112bluejay
  on:
    repo: thiefjack/WebStormTroopers
notifications:
  email: false
  slack:
    secure: FAKE_SLACK_KEY
